#!/usr/bin/env python

import os, os.path

print('Writing .extra_emscripten configuration file to user home directory ' + emscripten_config_directory)
# Remove .extra_emscripten from emsdk dir, since its presence is used to detect whether emsdk is activate in embedded mode or not.
try:
  os.remove(os.path.join(emsdk_path(), ".extra_emscripten"))
except:
  pass
